version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DATABASE_NAME}
      MYSQL_USER: ${WORDPRESS_DATABASE_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-p${WORDPRESS_DATABASE_PASSWORD}"]
      interval: 10s
      retries: 5
      timeout: 10s
    networks:
      - docker_backend-network
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      WORDPRESS_DATABASE_HOST: ${WORDPRESS_DATABASE_HOST}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
    networks:
      - docker_frontend-network
      - docker_backend-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql  
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - docker_frontend-network

networks:
  docker_frontend-network:
  docker_backend-network:
